### ISSUE TITLE
nem münködik

### ISSUE THREAD

**Issue by lasfer22** [palicz/wlsboti#1]
mindent jól álitotam be és csak át sétál a közin

**Comment by palicz** [comment]
Többen is tesztelik jelenleg is a programot, és nem tapasztaltunk hibákat.

> [!TIP]
> **Figyelmesen kövesd végig a telepítés folyamatát, mivel minden lépés fontos.**

**Comment by zenzty** [comment]
Ne felejts el **`belső nézetre`** váltani, hogy a karaktered ne látszódjon a játék ablakban.

**Comment by lasfer22** [comment]
jaa köszi

**Comment by lasfer22** [comment]
nagyon jól münködik kösziii
